version: "3.4"

services:
  app:
    image: ${DOCKER_IMAGE:-a4fd}:${DOCKER_TAG:-prod}
    restart: unless-stopped
    environment:
      - APP_ENV=production
	  - APP_URL=https://dashboard.solda.testingmachine.eu
    ports:
      - ${SERVER_PORT:-1077}:5000
